### ISSUE TITLE
光华之声不能用 汉声电台没有 期待

### ISSUE THREAD

**Issue by gtwebuser** [goolguy007/radioer#11]

**Comment by goolguy007** [comment]
光华之声前几天官网也不能听。刚刚他们才换了新的收听网址，我也相应修改了下代码。现在可以听了。最近一直在研究如果做汉声广播php，赞未有头绪。

**Comment by goolguy007** [comment]
光华之声已经修复。另外新增了汉声广播，收听愉快！

**Comment by gtwebuser** [comment]
赞👍，不知何因，发现除了对电台流地址开代理外，也必须对http://live.cooltv.top/tv/voh.php开启代理才能成功收听汉声，而收听光华就不需对你提供的网址开代理就就可收听。另外，汉生电台有AM及FM两台，不知上面是哪一台？

**Comment by goolguy007** [comment]
我已经更新代码和直播源，现在可以收听汉声的两个频道了。台湾大部分广播用的是hinet中华电信提供的技术，大陆对中华电信hinet的域名进行了DNS污染。所以要想收听这几个电台，要不直接翻墙收听，要不就修改host文件，比如ios可以下载安装shadowrocket软件并打开，按照图片所示添加host，并在规则里将hinet.net设置为直连即可正常收听台湾电台。
![C9C1B382-E033-4BB1-AEDC-E3100FBCB534](https://user-images.githubusercontent.com/61819065/226242307-faca823b-1597-4d12-bcdb-d9b13aeb324e.png)
![CC5AC0DB-C9E9-420A-9530-53931099FF00](https://user-images.githubusercontent.com/61819065/226242314-75f33623-4e6b-471a-b19a-d9e417723606.png)
