### ISSUE TITLE
订阅导入问题，我家里面的老电视，http://live.cooltv.top/tv.php 这个可以导入，其他gitee和github都不行

### ISSUE THREAD

**Issue by simlive** [goolguy007/radioer#12]
订阅导入问题，我家里面的老电视，http://live.cooltv.top/tv.php ，这个可以导入，其他gitee和github都不行

我就想问一下http://live.cooltv.top/tv.php，这个我知道是你个人搭建的，我也想搭建一个，我找了直播源，就是单纯想在线导入到电视上去，你用的什么平台搭建的呢，我想学习一下，不知道行不行，麻烦了

**Comment by goolguy007** [comment]
github本来被DNS污染了，gitee不清楚

**Comment by zuanshijia** [comment]
@simlive 使用Github就可以，找一个域名网站(推荐eu.org)注册好后申请好后弄个DNS代理给他挂到Github上面，有可能Github访问不了，请使用dev-sidecar软件进行访问，随后把直播源文件上传Github仓库里，再通过你注册的链接访问就行了。示例:你注册的域名是114514.com，你上传的是1.txt，你把域名挂到Github后你可以在地址栏输入114514.com/1.txt就行了，Github有些许延迟，需要等一下。那个直播源m3u8或者txt也可以，格式不一样，如有疑问请回复

**Comment by zuanshijia** [comment]
@simlive 不可能不能使用Github，把它当成一般的服务器用，实在不行就找个免费外链吧
