### ISSUE TITLE
关于在电视端用TiviMate软件，播放视频源部分失效的问题

### ISSUE THREAD

**Issue by GD2021** [goolguy007/radioer#2]
1、请问在电视端的TiviMate软件用TVradio源还是bjmobile.m3u源呢？
我用的后者，香港部分节点失效。
给您一个源网站https://iptvcat.com/home_8 仅供参考

**Comment by goolguy007** [comment]
❶ bjmobile.m3u 的源只有国内的省级卫视和CCTV等频道 
❷ TVradio的源包括了高清电台和电视台，CCTV和省级卫视只支持IPv6

**Comment by GD2021** [comment]
大佬，有些视频播放不了，是我播放软件的原因吗？您建议电视端用哪个软件。我把IPV6关了

**Comment by goolguy007** [comment]
有的视频播放不了是因为得翻墙或者需要ipv6的网络环境。如果是windows系统可以用potplayer，mac系统可以用iina或者影音宝
