### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by JING20212** [goolguy007/radioer#3]
大佬源地址是不是改ipv6了

**Comment by goolguy007** [comment]
是的 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月3日(星期二) 下午2:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[goolguy007/radioer] 请问 (#3)

**Comment by goolguy007** [comment]
> 大佬源地址是不是改ipv6了
卫视央视等频道改为ipv6地址了，之前是域名。之前也是只支持ipv6的。之所以改为ipv6地址是因为域名的话电信网络看不了
