### ISSUE TITLE
关于Android导入订阅源

### ISSUE THREAD

**Issue by LightGrass** [goolguy007/radioer#4]
我在使用diyp影音导入作者的源订阅时，遇到了无加载的情况

**Comment by goolguy007** [comment]
https://raw.githubusercontent.com/goolguy007/radioer/main/itv.txt 试试这个。内容同TVradio。可能是diyp不支持没有扩展名的订阅。

**Comment by LightGrass** [comment]
好像是它只支持#genre#开头的TXT格式

**Comment by goolguy007** [comment]
> 好像是它只支持#genre#开头的TXT格式

具体格式是怎样的？

**Comment by LightGrass** [comment]
我给你分享一个直播源看看，https://pastebin.com/raw/Dg5EDRXp

**Comment by goolguy007** [comment]
这样更新起来会比较麻烦一些 😂

**Comment by LightGrass** [comment]
hh，如果太麻烦就算了，我看看有没有其他法子
